devops/girder-worker/Dockerfile
devops/girder/Dockerfile

The style options branch has been merged.

Switch to using large_image master.

---

src/store/index.ts

Ignore hot keys when input elements are focused.

---

devops/girder/Dockerfile
package.json
src/components/ContrastHistogram.vue
src/components/DisplayLayer.vue
src/components/ImageViewer.vue
src/components/ValueSlider.vue
src/components/ViewerToolbar.vue
src/store/GirderAPI.ts
src/store/images.ts
src/store/index.ts
src/store/model.ts
src/views/dataset/DatasetInfo.vue
src/views/dataset/configuration/Configuration.vue
tsconfig.json

This currently disables the time value, as in all of the examples I've seen time is an incidental data value, not a stacking value.
Resolves #35.

Use XY index values.

---

package-lock.json
package.json
src/components/GirderLocationChooser.vue
src/components/ImageViewer.vue
src/layout/Menu.vue
src/store/GirderAPI.ts
src/views/Home.vue
src/views/dataset/ImportDataset.vue
src/views/dataset/NewDataset.vue
src/views/dataset/index.ts

Rename things to make them clearer.  Improve some formatting.
There are still many things to do (see issues and shared docs).  This will be added as commits to this PR or as separate PRs.

Many small cosmetic improvements.

---

src/views/dataset/DatasetInfo.vue

- Format the dataset information in a table
- Automatically create a default view if none exists

Improve the behavior of the initial dataset report

---

src/store/GirderAPI.ts
src/utils/parsing.ts
src/views/dataset/NewDataset.vue

This might still be missing some things that were requested, like a display of the time steps, Z values, etc., found during processing, and the opportunity to correct or deny such findings.

Parse uploaded files' filenames to determine dataset metadata

---

src/components/ViewerToolbar.vue
src/views/dataset/configuration/Viewer.vue

Move composition mode control to bottom of left side.

---

src/components/ViewerToolbar.vue

This also adds a tooltip to the sliders to tell how many values there are.

Make the slider/unroll layout more compact.

---

src/store/GirderAPI.ts
src/store/model.ts
src/views/dataset/DatasetInfo.vue
src/views/dataset/configuration/Viewer.vue

Set default colors for some named channels.

---

package-lock.json
package.json
src/App.vue
src/components/ImageViewer.vue
src/components/Snapshots.vue
src/store/model.ts

This adds a "Screenshot" button and dialog.
There are some different options.  The area and resolution can be 
- screen - this is the actual pixels on the screen.  Currently, this can only do one layer at a time due to a limitation in the canvas screenshot library that is employed; this will be fixed in the future.
- viewport - the area of the screen, but rendered from the source file.  This can be higher resolution.  The output will either be the native image size or no larger than the specified value or 10,000 in the maximal dimension.
- full - the entire image rendered from the source file.  The output will either be the native image size or no larger than the specified value or 10,000 in the maximal dimension.
The viewport and full options aren't available when one or more axes is …

Add a screenshot button and dialog to download images

---

src/components/Snapshots.vue

This only works for viewport or all, not screen.  There is no enforced maximum resolution for tiffs, whereas we limit jpegs and pngs to 10000 pixels since the entire jpeg or png must fit in 4Gb.

Support TIFF screenshots.

---

src/components/Snapshots.vue

The color is red, no fill.  The default for the bounding box is inset 20 pixels from the edge.

Adjust snapshot bounding box.

---

src/App.vue
src/components/ImageViewer.vue
src/components/Snapshots.vue
src/store/GirderAPI.ts
src/store/index.ts
src/store/model.ts
src/views/dataset/configuration/Configuration.vue

Not done yet:
- Tags aren't implemented at all
- Search doesn't exist
- You can't get to the snapshot from the route
Other pending features:
- Switch from a pulldown of snapshots to a list
- Default name involving the current date
- Store a thumbnail
Closes #110.  Closes #113.

Add Snapshots

---

src/components/Snapshots.vue

Use width/height rather than right/bottom for dimensions.

---

package-lock.json
src/components/Snapshots.vue

The list should look better and show tags and description.
Closes #112.  Closes #114.  Closes #82.

Add tag support, change snapshots to list

---

src/App.vue

Calculate default snapshot boundingbox after panel open.

---

src/components/DisplaySlice.vue
src/components/ViewerToolbar.vue
src/store/GirderAPI.ts
src/store/images.ts
src/store/index.ts
src/store/model.ts

Closes #7.  Closes #28.  Closes #85.

Initial implementation of max-merge.

---

src/components/ImageViewer.vue
src/store/images.ts

Adjust the histogram shown when max-merge is selected.

Improve releasing GL contexts when switching datasets.

---

src/components/Snapshots.vue
src/utils/date.ts
src/views/dataset/DatasetInfo.vue

Change the default filename for image download

---

src/components/ImageViewer.vue
src/store/GirderAPI.ts
src/store/index.ts

When the map is idle, precache histograms and full range images for the longest axis.
Closes #124.  Closes #95.

Precache histograms and full range images.

---

.eslintrc.js
src/components/Snapshots.vue

Make snapshot list sortable using v-data-table

---

package-lock.json
package.json

Bump vuetify to 2.3.11 for colorPicker fix (vuetify#12289)

---

src/components/ContrastHistogram.vue

Rename "Reset to saved" button to "Revert to saved"

---

src/components/DisplayLayer.vue
src/components/DisplaySlice.vue

When setting a slice to "Constant", use the current displayed value

---

package-lock.json
package.json

This fixes the build errors that popped up on master after #135 
I'm not sure why that suddenly became an issue.

Bump "@types/d3-scale" to match with "d3-scale" version

---

src/components/ValueSlider.vue
src/components/ViewerToolbar.vue

Make sliders show upper bounds and start at 1

---

package-lock.json
package.json
src/components/ImageViewer.vue

This should make the browser somewhat more responsive, as it will have fewer queued requests after panning or adjustments.

Used a shared tile queue across layers.

---

src/components/DisplayLayer.vue
src/components/DisplaySlice.vue
src/components/ValueSlider.vue

Fix layer slice indexes not updating sometimes, and starting from 0

---

src/components/AnnotationBrowser/AnnotationCSVDialog.vue
src/layout/UserMenu.vue
src/store/AnnotationsAPI.ts
src/store/index.ts
src/utils/annotation.ts

If specified in the environment, use a different default server URL and auto log in a guest user.
This also fixes some formatting issues.

Demo support

---

package-lock.json
package.json

This is in preference to #223.

Update packages, especially geojs.

---

package-lock.json
package.json
src/components/ImageViewer.vue

Use nearest neighbor when zoomed further than base pixels.

---

.gitignore
src/components/AnnotationBrowser/AnnotationList.vue
src/components/AnnotationBrowser/AnnotationToggles.vue
src/components/AnnotationViewer.vue
src/store/annotation.ts
src/store/index.ts
src/store/model.ts
src/utils/annotation.ts

Closes #233, #236,  #240, #245

Add select tool

---

src/views/dataset/MultiSourceConfiguration.vue

Added stride options per channel when needed

Added multi-image tiff support

---

src/components/AnnotationBrowser/AnnotationToggles.vue
src/components/AnnotationViewer.vue
src/store/index.ts

Clear and concise UI
Some minor bug fixes

Changed UI of: Annotation Browser -> Annotation controls

---

package-lock.json
package.json
src/components/AnnotationViewer.vue
src/components/ImageViewer.vue
src/components/ViewerToolbar.vue
src/store/index.ts
src/views/dataset/configuration/Configuration.vue

This also split a large function into several functions in the ImageViewer's draw routine.  Multiple annotation layers are created (one per unrolled map).

Unroll layers.

---

src/components/DisplayLayer.vue
src/components/ImageViewer.vue
src/views/dataset/MultiSourceConfiguration.vue

- Small fixes, refactor and UI changes (15, 16)
- Replace stride option with a new variable (14)
- Added Z Max Merge switch to each channel (18)

More UI changes

---

src/components/AnnotationBrowser/AnnotationActions.vue
src/components/AnnotationViewer.vue
src/store/AnnotationsAPI.ts
src/store/annotation.ts

Open a dialog when wlicking "TAG SELECTED" in the action menu of the browse annotation panel.
Remove the embedding of IAnnotation in geojs annotations ("storedAnnotation" option) which caused bugs when updating the IAnnotation.

Feature: add tags to selected annotations

---

src/components/DisplayLayer.vue

Labels of switches "Channel on/off" and "Z max-merge" moved to first row only.

Put layer labels only on the first row

---

src/components/AnnotationBrowser/AnnotationList.vue

It also fixes the checkbox alignment problem in this UI.
Closes #311

Remove channel from annotation list UI

---

src/store/index.ts

Change default value of showTooltips to false

---

src/components/AnnotationBrowser/AnnotationToggles.vue
src/components/AnnotationViewer.vue
src/store/index.ts
src/tools/creation/templates/AnnotationConfiguration.vue
src/utils/annotation.ts

Instead of filtering annotations to check if they should be displayed, display and filter all annotations for each layer.
TODO: select-layer component outputs an index, should it output an ID?
Closes #310

Change annotation display mechanism

---

src/App.vue
src/components/AnnotationBrowser/AnnotationToggles.vue
src/components/AnnotationViewer.vue
src/components/DisplayLayer.vue
src/components/DisplayLayers.vue
src/components/ImageViewer.vue
src/components/Snapshots.vue
src/components/ViewerToolbar.vue
src/main.ts
src/store/GirderAPI.ts
src/store/index.ts
src/store/model.ts
src/tools/creation/ToolCreation.vue
src/tools/toolsets/Toolset.vue
src/utils/annotation.ts
src/views/dataset/configuration/Viewer.vue

Add hotkeys mentionned in #247, including the tool hotkeys.
Replace old custom key support.
Fix a minor bug.
Closes #247

Add hotkeys

---

src/store/index.ts

This showed up when I create an instance and started it with only two data sets.

When there are very few recent configurations, we showed an error

---

src/components/AnnotationViewer.vue

Remove XY, Z, T
Add list index and properties
Closes #332

Customize tooltips

---

src/components/AnnotationViewer.vue
src/store/GirderAPI.ts
src/store/annotation.ts
src/store/model.ts
src/utils/annotation.ts

IndexXY, IndexZ, IndexT, IndexC can be undefined
Closes #332

Reformat annotation tooltips, fix unrolling

---

src/components/AnnotationViewer.vue

Ready to merge immediately
Closes #282

Fix layer mode disabled by turning off annotations

---

src/components/AnnotationViewer.vue
src/components/LayerSelect.vue
src/components/TagPicker.vue
src/store/AnnotationsAPI.ts
src/store/GirderAPI.ts
src/store/PropertiesAPI.ts
src/store/index.ts
src/store/model.ts
src/utils/annotation.ts
src/utils/fetch.ts
src/views/dataset/DatasetInfo.vue

Factorize fetching all pages from an endpoint, which fixes errors (#350)
Rework draw logic which fixes untracked bugs and performance problems (#350, #329)
Get tags from annotations in addition to tools, which fixes #348
Add a GeoJSAnnotation ts interface
Fix some reactivity issues
Ready to merge right away
Closes #329
Closes #350
Closes #348

Rework draw logic, fetch pages and show more tags

---

devops/girder/Dockerfile

#352 changed what was installed unintentionally.

Explicitly install girder plugins.

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/helpers/tasks.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/annotation.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/property.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/workerInterfaces.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/workerPreviews.py
src/components/AnnotationBrowser/AnnotationProperties/PropertyBody.vue
src/components/ChannelSelect.vue
src/components/DisplaySlice.vue
src/components/LayerSelect.vue
src/components/PropertyWorkerMenu.vue
src/components/WorkerInterfaceValues.vue
src/store/AnnotationsAPI.ts
src/store/PropertiesAPI.ts
src/store/annotation.ts
src/store/model.ts
src/store/properties.ts
src/tools/creation/ToolCreation.vue

Also update and rework worker interfaces
See [this PR](https://github.com/arjunrajlaboratory/ImageAnalysisProject/pull/2) for worker example

Remove worker interface merging

---

src/utils/annotation.ts

Darken annotations stroke

---

src/components/Snapshots.vue
src/store/model.ts

Also add a new IGeoJSLayer type.

Add screenshot viewport feature

---

src/components/AnnotationViewer.vue

Display annotations of all images in max-merge

---

src/components/AnnotationWorkerMenu.vue
src/store/index.ts
src/store/properties.ts
src/tools/toolsets/ToolItem.vue
src/tools/toolsets/Toolset.vue

Move annotation worker menu and refactor

---

src/components/ContrastHistogram.vue
src/store/GirderAPI.ts

Add zoom to histograms and fix the clamping of absolute values in the histogram
Closes #366

Zoom histogram

---

src/components/AnnotationBrowser/AnnotationList.vue

Reduced the number of decimal points to 2
Closes #392

Reduce number of decimal points of property values

---

src/components/AnnotationBrowser/AnnotationBrowser.vue
src/components/AnnotationBrowser/AnnotationProperties.vue
src/components/AnnotationBrowser/AnnotationProperties/Property.vue
src/components/AnnotationBrowser/AnnotationProperties/PropertyCreation.vue

Move property checkboxes to the annotations pannel

---

src/components/ImageViewer.vue

Fix reset of osm layers when changing dataset

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/connections.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/connections.py
public/config/templates.json
src/components/AnnotationViewer.vue
src/store/AnnotationsAPI.ts
src/store/annotation.ts
src/store/model.ts
src/tools/creation/ToolCreation.vue

Add remove connections tool

---

src/components/AnnotationBrowser/AnnotationList.vue
src/components/AnnotationViewer.vue
src/store/annotation.ts

Fix annotation list checkboxes for selection

---

public/config/templates.json
src/components/CustomFileManager.vue
src/components/DisplayLayer.vue
src/components/DisplayLayerGroup.vue
src/components/DisplayLayers.vue
src/components/HotkeySelection.vue
src/store/annotation.ts
src/store/index.ts
src/store/properties.ts
src/tools/ToolEdition.vue
src/tools/ToolIcon.vue
src/tools/creation/ToolConfiguration.vue
src/tools/creation/ToolCreation.vue
src/tools/creation/templates/AnnotationConfiguration.vue
src/tools/creation/templates/DockerImage.vue
src/tools/creation/templates/TagAndLayerRestriction.vue
src/tools/toolsets/ToolItem.vue
src/views/dataset/DatasetInfo.vue

All of these issues are "small":
Close #405 
Close #408 
Close #410 
Close #406 
Close #407 
This one is bigger:
Close #409

Batch of small alpha-project issues

---

src/components/AnnotationBrowser/AnnotationList.vue
src/components/AnnotationViewer.vue

Also reformat the computation of hovered annotation
Close #418

Fix clicking an annotation change page

---

src/components/ImageViewer.vue

On Mac: command+del
On Windows and Linux: ctrl+del
Close #404

Add (command/ctrl)+del shortcut

---

src/components/AnnotationWorkerMenu.vue

Add a border to the menu
Close #416

Make worker menu stand out

---

src/store/index.ts

Avoid fetching annotation twice

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/connections.py

(A quick fix)
If there is no annotation to connect to, the server used to return a 500 error
Also reformat the code a little bit

Fix connectTo when there is no connection

---

src/store/annotation.ts

Change the endpoint to delete multiple annotations

Use endpoint to delete multiple annotations

---

src/components/AnnotationBrowser/AnnotationList.vue
src/components/AnnotationViewer.vue
src/store/AnnotationsAPI.ts
src/store/annotation.ts
src/store/filters.ts
src/utils/fetch.ts

Improve performance when the number of annotations grows

Scaling issues

---

src/components/Snapshots.vue
src/store/index.ts
src/store/model.ts
src/utils/routeMapper.ts

Fixes some bugs which made the viewer sometimes reset
Close #432

Make dataset updates less frequent

---

src/views/dataset/MultiSourceConfiguration.vue

Also make better typescript
Close #448

Make guesses of variable immutable only with nd2

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/__init__.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/annotation.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/connections.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/datasetView.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/history.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/propertyValues.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/helpers/proxiedModel.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/annotation.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/connections.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/datasetView.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/history.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/property.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/propertyValues.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/workerInterfaces.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/workerPreviews.py
src/components/AnnotationBrowser/AnnotationActions.vue
src/components/AnnotationViewer.vue
src/main.ts
src/store/GirderAPI.ts
src/store/annotation.ts
src/store/index.ts
src/store/model.ts
src/utils/debounce.ts
src/views/datasetView/Viewer.vue

Must be merged after #457 
Fetch properties when configuration changes
Fetch propertyValues when dataset changes
Move the watchers up in the component tree
Close #455

Fetch property values when config changes

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/helpers/proxiedModel.py

Fix the cacheBodyJson wrapper

---

src/components/Snapshots.vue

Fix NaN values when typing in width/height of Snapshot

---

src/tools/creation/ToolCreation.vue
src/tools/creation/templates/AnnotationConfiguration.vue

@arjunrajlab
I added an automatic tag but the auto naming of the annotation becomes redundant
What do you think?
Close #454

Add auto tag of annotations

---

src/components/AnnotationWorkerMenu.vue

Just a small update on the worker menu

Minor UI update.

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/__init__.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/helpers/proxiedModel.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/documentChange.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/history.py

Separate the history entry and the document changes to avoid having a huge document
Closes #492

Break the history entry into multiple documents

---

devops/girder/annotation_client/annotation_client/utils.py
src/components/AnnotationBrowser/AnnotationProperties/Property.vue
src/components/AnnotationBrowser/AnnotationProperties/PropertyList.vue
src/components/AnnotationWorkerMenu.vue
src/store/annotation.ts
src/store/jobs.ts
src/store/model.ts
src/store/properties.ts

To be merged after #485 
Follow the instructions of #485 for the docker images of the workers
This is [the commit](https://github.com/arjunrajlaboratory/ImageAnalysisProject/commit/6b6f3f9f70c073634be908ea2d920f1dffcfabb1) in the [example branch](https://github.com/bruyeret/ImageAnalysisProject/tree/example-branch) of the image analysis project containing an example on how to use it in a worker
It is exactly the same function as with property workers
Part of #475

Add progress/notifications for annotation workers

---

src/components/ImageViewer.vue
src/store/AnnotationsAPI.ts
src/store/annotation.ts
src/store/model.ts
src/utils/fetch.ts

When downloading annotations (or annotation connections), show this linear progress:
When downloading of annotations and caching of dataset is done, show this green alert:
Close #437
Close #475

Add annotation fetching progress and green tooltip

---

src/App.vue
src/components/AnnotationViewer.vue
src/components/ImageViewer.vue
src/store/annotation.ts
src/utils/v-mousetrap.ts

Select annotations using shift+click or shift+drag
Close #427

Quick select

---

src/components/CustomFileManager.vue
src/girder/components.ts
src/girder/index.ts
src/girder/shims-girder.d.ts
src/views/Home.vue

Add search bar to the custom file manager

---

package-lock.json
package.json
src/components/AnnotationBrowser/AnnotationActions.vue
src/components/AnnotationBrowser/AnnotationCSVDialog.vue

Add Papaparse to dependecies, fix csv export

---

src/components/AnnotationBrowser/AnnotationCSVDialog.vue
src/components/AnnotationBrowser/AnnotationExport.vue

Add download file name option

---

src/views/dataset/MultiSourceConfiguration.vue

Remove offset on dimensions with multiple files

---

src/store/model.ts
src/tools/creation/ToolTypeSelection.vue

Add description to annotation workers

---

src/components/ImageOverview.vue
src/components/ImageViewer.vue
src/components/Snapshots.vue
src/components/ViewerSettings.vue
src/store/images.ts
src/store/index.ts
src/store/model.ts

Add overview panel

---

src/components/DisplayLayer.vue

Fix and improve color picker

---

src/components/ContrastHistogram.vue

Fix bound checks when typing contrast values

---

src/tools/creation/templates/AnnotationConfiguration.vue

Default "useAutoTags" to false for edit mode

---

src/store/GirderAPI.ts
src/store/index.ts
src/views/Home.vue

This doesn't close any issue
This PR fixes bugs that occurs at login
You don't need to review @arjunrajlab, but you can see that when logged out the file manager was always there

Fix minor bugs at login

---

src/components/AnnotationBrowser/AnnotationFilters.vue
src/store/filters.ts

Add current frame filter

---

src/components/AnnotationViewer.vue
src/components/ViewerSettings.vue
src/store/index.ts
src/utils/annotation.ts

Add point annotation scaling options

---

src/store/index.ts

This reverts commit da686bb70c8eca20d0a167ce36e564809b9f7304.
Close #536

Revert "Make dataset updates less frequent"

---

src/App.vue
src/components/DisplayLayer.vue
src/components/DisplayLayers.vue
src/components/HelpPanel.vue
src/components/HotkeyDescription.vue
src/components/ImageViewer.vue
src/components/ViewerSettings.vue
src/components/ViewerToolbar.vue
src/main.ts
src/tools/toolsets/ToolItem.vue
src/utils/v-description.ts
src/utils/v-mousetrap.ts

To add feature descriptions, see `ViewerSettings.vue`.
For example:
```
v-description="{
section: 'Settings',
title: 'Point annotations size',
description:
'Set size of the point annotations and their behavior when zooming'
}"
```
Close #535

Hotkeys hud

---

src/components/AnnotationBrowser/AnnotationProperties/Property.vue
src/components/AnnotationWorkerMenu.vue

Fix height of progress bar with text

---

src/App.vue

Increase z-index of menus to put them in front of images

---

src/views/dataset/MultiSourceConfiguration.vue

Enable fast mode for multi-file source

---

devops/girder/annotation_client/annotation_client/annotations.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/annotation.py

It was indeed a bug!
It should be fixed now
Close #530

Fix getAnnotationsByDatasetId when no shape is used

---

src/components/Snapshots.vue

Minor edits to wording and spacing.

Updated Snapshots with minor UI edits

---

src/App.vue
src/components/AnnotationBrowser/AnnotationBrowser.vue
src/components/AnnotationBrowser/AnnotationCSVDialog.vue
src/components/AnnotationBrowser/AnnotationExport.vue
src/components/AnnotationBrowser/AnnotationImport.vue
src/components/DisplayLayer.vue
src/components/DisplayLayers.vue
src/components/ImageViewer.vue
src/components/Snapshots.vue
src/components/UISettings.vue
src/components/ViewerSettings.vue
src/components/ViewerToolbar.vue

Added and edited HUD text throughout the UI

HUD text updates

---

src/components/Snapshots.vue

Some errors I didn't notice from PR #555 
`justify-left` doesn't exist, it should be `justify-start` (see errors in the console)
eslint doesn't accept two newlines one after each other

Fix snapshots error

---

src/store/index.ts

Fix global z max merge toggle

---

src/components/CustomFileManager.vue
src/components/FileManagerOptions.vue

File manager reload items and progress

---

src/components/ImageViewer.vue
src/components/ViewerSettings.vue
src/store/index.ts
src/utils/compositionModes.ts

The base composition modes are the one that work with images that have a black background
The advanced ones sometimes kind of work
Close #504

Compositing options

---

src/views/Home.vue
src/views/dataset/NewDataset.vue

Doing `this.files = ...;` didn't work
Close #590

Fix normal upload

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/system.py

I moved the maxmerge folder into the dataset folder but there are maybe paths to change somewhere that I didn't notice
What do you think @manthey?
Close #557

Move maxmerge folder into dataset folder

---

src/components/GirderLocationChooser.vue
src/views/dataset/NewDataset.vue

It takes all steps into account and uses a weight per step to account for the inequal time taken per step
Close #585

Add a quick import progress

---

src/views/dataset/MultiSourceConfiguration.vue

Use filename variables only when uploading several files

---

src/components/CustomFileManager.vue
src/layout/BreadCrumbs.vue
src/store/GirderAPI.ts
src/store/girderResources.ts
src/store/model.ts
src/views/dataset/MultiSourceConfiguration.vue
src/views/dataset/NewDataset.vue

I replaced the select component with a location picker
I also did minor changes to make the design of this feature simpler
Tell me if there is anything to change @arjunrajlab 
Close #562

Add the "Add dataset to collection" option in breadcrumbs

---

src/views/Home.vue
src/views/dataset/NewDataset.vue

Add default location when using Home component upload

---

src/components/AddDatasetToCollection.vue
src/components/AlertDialog.vue
src/layout/BreadCrumbs.vue
src/views/configuration/ConfigurationInfo.vue

What do you think @arjunrajlab?
Fixes request changes of #598 
Close #563

Updated UI to Collection view 

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/annotation.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/connections.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/helpers/proxiedModel.py

The old cacheBodyJson was not clean
It used to replace the getBodyJson method which is very dangerous
Instead, add a kwargs named "memoizedBodyJson" to the function call
This may fix #602

Fix memoization of bodyJson

---

src/components/AnnotationViewer.vue
src/store/properties.ts

Removed the master property name and only show subproperties.

Changed property name in tooltip display to simplify

---

src/components/ImageViewer.vue

Seems to fix reactivity bug. Tested on many datasets and seems to work fine.

marked as raw

---

.github/workflows/main.yaml
.github/workflows/wasm.yaml

Also run WASM workflow on PRs from forked repos

Prevent actions from running twice per PR

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/annotation.py
src/components/AnnotationViewer.vue
src/components/ImageViewer.vue
src/store/AnnotationsAPI.ts
src/store/annotation.ts
src/store/model.ts
src/tools/creation/ToolConfigurationItem.vue
src/tools/creation/templates/AnnotationConfiguration.vue
src/utils/annotation.ts

Add annotation color property in the advanced panel of annotation tools
Fix annotation colors not updating with the layer color
Fix setting for scalebar
Close #642

Annotation color

---

itk/MaskToBlob/main.cxx
public/config/templates.json
src/components/AnnotationBrowser/AnnotationActions.vue
src/components/AnnotationViewer.vue
src/components/ImageOverview.vue
src/components/ImageViewer.vue
src/components/SamToolMenu.vue
src/components/ViewerToolbar.vue
src/geojs.d.ts
src/pipelines/computePipeline.ts
src/pipelines/samPipeline.ts
src/store/AnnotationsAPI.ts
src/store/GirderAPI.ts
src/store/annotation.ts
src/store/filters.ts
src/store/index.ts
src/store/model.ts
src/tools/toolsets/Toolset.vue
src/utils/annotation.ts
src/utils/itk.ts
src/views/dataset/MultiSourceConfiguration.vue

Add SAM annotation tool features requested in #646 
Note: you need to rebuild the itk pipeline for SAM because of a small change (`npm run emscripten-build`)
Close #646

SAM tool important features

---

src/components/AnnotationBrowser/AnnotationList.vue
src/components/ImageViewer.vue
src/store/index.ts
src/utils/annotation.ts

It is part of #643 but there is no change in the zoom when clicking the annotation in the list
So this PR will not close the issue but it is a step in the right direction

Add a mechanism to center the view on the annotation when clicking in the list

---

src/views/dataset/MultiSourceConfiguration.vue
src/views/dataset/NewDataset.vue

Close #613
- Better guess for dataset name
- Max height for the file list
- Show loading and prevent submit until all variables are computed

Fix UI when uploading many files

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/connections.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/connections.py
src/components/AnnotationBrowser/AnnotationActions.vue
src/components/AnnotationBrowser/DeleteConnections.vue
src/store/annotation.ts

Add an action button to delete connections

---

public/config/templates.json
src/components/AnnotationViewer.vue
src/store/annotation.ts
src/store/index.ts
src/store/model.ts

Add tool to connect or disconnect annotations using click

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/annotation.py

This resolves slow annotation look ups

Add a datasetId index

---

src/components/AnnotationBrowser/AnnotationImport.vue

Fixes https://github.com/Kitware/UPennContrast/issues/673

Fixed import to read color

---

src/components/AnnotationViewer.vue
src/components/ImageViewer.vue
src/components/PixelScaleBarSetting.vue
src/components/ScaleSettings.vue
src/components/ViewerSettings.vue
src/store/index.ts
src/store/model.ts

Pixel scalebar

---

src/store/index.ts
src/views/Home.vue

Keep a global folder location

---

src/components/AnnotationViewer.vue
src/components/Snapshots.vue
src/store/model.ts

Snapshot fixes

---

src/components/AnnotationBrowser/AnnotationList.vue

Fix annotation sorting

---

src/components/AnnotationBrowser/AnnotationCSVDialog.vue

Cosmetic changes to CSV download

---

src/components/ImageViewer.vue

Move progress bars to the bottom right corner

---

src/components/AnnotationBrowser/AnnotationProperties/PropertyCreation.vue
src/components/PropertyWorkerMenu.vue
src/components/WorkerInterfaceValues.vue
src/store/model.ts
src/store/properties.ts

The property is `displayOrder` and is optional
Close #678 
Close #681

Add display order to worker interface

---

README.md
src/App.vue
src/components/HelpPanel.vue
src/components/ImageViewer.vue
src/components/ServerStatus.vue
src/store/index.ts

Add help button and link to documentation

---

src/components/AnnotationBrowser/AnnotationProperties/PropertyCreation.vue

Removes repeated words in property autonaming to avoid "blob Blob blob" things from happening.

Remove repeat words

---

src/components/Snapshots.vue

Mostly, people want to get the composite, so I made that the first option. I also put (zip) after "All layers" so that people know they will be getting a zip of the individual layers.

Change default to composite

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/propertyValues.py
src/components/AnnotationBrowser/AnnotationCSVDialog.vue
src/components/AnnotationBrowser/AnnotationList.vue
src/components/AnnotationViewer.vue
src/store/model.ts
src/store/properties.ts
src/utils/paths.ts

You need to rebuild girder for the validation of None or strings to pass.
Close #721

Accept strings and null as property values

---

src/App.vue
src/components/ColorPickerMenu.vue
src/components/DisplayLayer.vue
src/components/ImageViewer.vue
src/components/LayerInfoGrid.vue

Adds a pop-up contrast panel, allowing for quick contrast adjustment for all channels.

Constrast panel

---

src/tools/creation/templates/AnnotationConfiguration.vue

Disable auto tags when editing the tools

---

src/tools/creation/ToolCreation.vue
src/tools/toolsets/Toolset.vue

Tool hotkey fix and tooltip

---

src/components/FileManagerOptions.vue
src/components/Snapshots.vue

Fix snapshot refreshing page on creation with a small refactor

---

src/layout/UserMenu.vue
src/store/index.ts
src/views/Home.vue

- Fix blinking of user menu (login screen)
- Fix loading of recent datasets sometimes not happening
- Disable tooltip when there is nothing to show in the tooltip

Small fixes

---

src/components/CustomFileManager.vue
src/components/FileManagerOptions.vue
src/store/GirderAPI.ts
src/views/Home.vue

Add the "Download" option for items and files and the "Browse" option for datasets
Close #740

File manager options

---

src/components/AnnotationBrowser/AnnotationImport.vue
src/store/PropertiesAPI.ts

I fixed the import of annotation properties
Overwriting annotations works on my side, are you sure that annotations are not removed?
Close #751
Close #752

Fix import of annotation properties

---

devops/girder/Dockerfile
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/__init__.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/user_assetstore.py
src/components/FileManagerOptions.vue
src/girder/index.ts
src/store/GirderAPI.ts
src/store/index.ts

Rebuilding girder is needed
`docker-compose build girder`
Close #477

Add feature to move folder to a different assetstore

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/system.py

This won't change existing users unless they are saved.

Make users non-public

---

src/tools/creation/ToolCreation.vue
src/tools/creation/ToolTypeSelection.vue
src/tools/creation/templates/AnnotationConfiguration.vue

Use `annotationShape` as for Property workers
Close #744

Add a support for annotation worker shape label

---

devops/girder/annotation_client/annotation_client/annotations.py

Made a getPropertyById to get property information from a propertyId.
Also, fixed the naming convention for some paths that are for property values.

Updated API to add getPropertyById

---

src/components/AnnotationViewer.vue

Coordinates should not have a z coordinate
You can merge right away if important

Fix connection display

---

README.md
src/store/index.ts

Add documentation and fix environment variables.

Fix environment variables

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/annotation.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/annotation.py
src/components/AnnotationBrowser/AnnotationImport.vue
src/components/AnnotationBrowser/AnnotationList.vue
src/components/AnnotationViewer.vue
src/store/AnnotationsAPI.ts
src/store/annotation.ts
src/store/model.ts

You need to rebuild girder because of the addition of an endpoint to edit multiple annotations at the same time
Close #750

Color selected

---

devops/girder/plugins/girder-claude-chat/girder_claude_chat/__init__.py
devops/girder/plugins/girder-claude-chat/system_prompt_1.txt

The more comprehensive system prompt should give a better experience. In theory, the prompt caching should be much more cost-effective and faster. I didn't notice much difference, but we will see.

More comprehensive system prompt and prompt caching

---

devops/girder/annotation_client/annotation_client/annotations.py

I tried many variations, ultimately ChatGPT o1-preview was the only one smart enough to figure out the problem for me :).

Added function to delete multiple annotations at once

---

package.json
pnpm-lock.yaml

Fixed in geojs PR 1334 https://github.com/OpenGeoscience/geojs/pull/1334
Close #773

Fix snapshots by bumping geojs

---

src/components/TagPicker.vue

Made the focus return after adding each tag. Many users were sort of confused or annoyed a the tag picker automatically going to add more tags.

Slight tweak to the tag picker interface

---

src/components/AnnotationBrowser/AnnotationProperties/PropertyCreation.vue

Fixes the property creation logic to guide the user through property creation more clearly. It also fixes some of the reset logic, which was broken.

Fix property creation logic

---

src/components/AnnotationBrowser/AnnotationList.vue
src/store/annotation.ts

When you click "tag selected", it now has an option to replace the existing tags.

Replace tags

---

TOOLS.md
public/config/templates.json
src/components/AnnotationViewer.vue
src/store/model.ts
src/tools/creation/ToolConfigurationItem.vue
src/tools/creation/ToolCreation.vue
src/tools/creation/templates/AnnotationConfiguration.vue

Added tools for tagging either by clicking or lassoing.

Click to tag tool

---

devops/girder/plugins/girder-claude-chat/girder_claude_chat/__init__.py

Updated chatbot to use new Sonnet version.

Updated to new Sonnet version

---

src/components/NimbusTooltip.vue

Had to increase Z to 1000 so that the tooltips display above the annotation layers.

Increase tooltip Z

---

src/components/TagCloudPicker.vue

Added color picker to the things you can do based on clicking a tag.

Add color picker to tag chevron

---

src/components/AnnotationBrowser/AnnotationCSVDialog.vue

Added some requested options for listing only specific properties for download.

Improve csv download

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/annotation.py
src/store/index.ts
src/store/model.ts
src/utils/annotation.ts

Added support for rectangle annotation type.
Edited annotation.py, which I think has the schema.

Added support for rectangle annotations

---

src/components/AnnotationViewer.vue
src/utils/annotation.ts

Very minor performance enhancement, consolidated the annotation creation into a single call.

Slight speedup on consolidating

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/annotation.py

The orjson library is substantially faster than the built in python library at he expense of being less flexible.  Here, we strip out the access control dictionaries from each annotation, convert the mongo id to a string, then use orjson to serialize.  Further, rather than load the entire set of annotations into memory and serialize them in one shot, we stream them from the database and serialize them individually. When there are enough of them for efficiency, we yield them to the output function.  This allows the data to start being returned before the database finishes, and, if the connection is interrupted, to stop pulling from the database when it is no longer useful.
orjson is included as part of large_image, so we don't need to add it to the dependencies.

This uses the orjson library to serialize annotations.

---

package.json
pnpm-lock.yaml
src/components/AnnotationViewer.vue
src/store/model.ts

Converted to loops in many places.
Removed looped object creation in at least one place.

Removed several function calls

---

src/App.vue
src/views/dataset/NewDataset.vue

Fixes a problem where hitting return goes down the wrong path.
Fixes the Upload Data button in the top navigation bar.

Fix upload buttons

---

src/components/AnnotationContextMenu.vue

After running the context menu, we want to reset apply to same tags.

Reset apply to all tags

---

src/components/AnnotationViewer.vue

Was removing annotation from the wrong layer.

Fixed lasso selection tool

---

src/views/dataset/NewDataset.vue

Reads environment variable VITE_MAX_TOTAL_FILE_SIZE to specify max total file size (over all files) in MB.

Added max file size limit

---

src/views/dataset/NewDataset.vue

When uploading a file, this allows you to add more files to the upload (much requested feature).

Add files to upload

---

src/store/jobs.ts
src/store/progress.ts

Checks in case the job completes very fast

---

src/views/Home.vue

Recents list was going out of sync a lot. Now it is less reliant on watchers.

Fixed recents list

---

src/components/FileManagerOptions.vue

Display list of files in a table and update button during deletion.

Updated UI for delete file

---

src/store/annotation.ts
src/store/progress.ts
src/store/properties.ts

Adds progress bars in the progress manager. This allows for users to track the progress even if the UI is closed.

Adds progress bars to the tracking of annotation and property workers

---

package.json
pnpm-lock.yaml
src/components/CustomFileManager.vue
src/components/FileItemRow.vue
src/components/NimbusTooltip.vue
src/components/ServerStatus.vue
src/girder/index.ts
src/tours/AdvancedUploadTour.yaml
src/utils/date.ts
src/views/Home.vue

Updated the home screen UI:
1. Updated the App bar server icon to be more modern than the floppy disk.
2. Added colored icons to file list to make items easier to distinguish.
3. Moved chips around and restyled them to make them less intrusive and more informative.
4. Changed file dropzones to make them more descriptive and intuitive.
5. Updated tour accordingly.

Update home UI

---

devops/girder/plugins/girder-claude-chat/girder_claude_chat/__init__.py

Prompt caching moved out of beta.

Removed beta.prompt_caching from Claude API call

---

src/components/WorkerInterfaceValues.vue
src/plugins/tour.scss
src/plugins/tour.ts
src/tools/creation/ToolCreation.vue
src/tools/creation/ToolTypeSelection.vue
src/tools/creation/templates/AnnotationConfiguration.vue
src/tools/toolsets/ToolItem.vue
src/tools/toolsets/Toolset.vue
src/tours/AddManualBlobToolTour.yaml
src/tours/TestToolTourstep.yaml
src/utils/strings.ts

Added a tour for adding a DAPI blob tool.
Also, added automatic ID generation for toolsets and worker value lists (interface items from the worker).

Added a tour for adding a DAPI blob

---

src/components/WorkerInterfaceValues.vue
src/plugins/tour.scss
src/plugins/tour.ts
src/tools/creation/ToolCreation.vue
src/tools/creation/ToolTypeSelection.vue
src/tools/creation/templates/AnnotationConfiguration.vue
src/tools/toolsets/ToolItem.vue
src/tools/toolsets/Toolset.vue
src/tours/AddManualBlobToolTour.yaml
src/tours/TestToolTourstep.yaml
src/utils/strings.ts

1. Streamlined the UI for adding a tool to remove the extra click.
2. Gives a panel view for tools that is more organized and discoverable.
3. Also, this makes the add tool tour work better, because I was having some clipping issues with the previous floating list.

Streamline toolset UI

---

public/config/templates.json
src/components/AnnotationViewer.vue
src/tools/creation/ToolTypeSelection.vue
src/utils/polygonSlice.ts

One common request from users is for a blob editing tool. This PR implements a blob editing tool that allows for blob editing. Rather than a brush and eraser ala Photoshop, it instead implements a "line splice" tool. You can just draw to add and remove from your blob.

Add blob editing tool

---

src/components/AnnotationWorkerMenu.vue

Minor fix to styling:
Better styling for the panel
Subtle drop shadow
Added scroll bar for large numbers of interface elements

Fixed styling for annotation worker menu

---

src/components/MovieDialog.vue
src/components/Snapshots.vue

Adds a scalebar to snapshots, both for download and on the screen.
The only thing I couldn't quite figure out was how to put the text on the line. I couldn't figure out how to add the label to the geojs line annotation.

Snapshot scalebar

---

src/components/AnnotationBrowser/AnnotationExport.vue

Chunked up the JSON export to avoid very large string variables.
Added progress indicators to give visual feedback.

Optimize JSON export

---

src/girder/index.ts
src/layout/BreadCrumbs.vue
src/store/GirderAPI.ts
src/store/girderResources.ts
src/store/index.ts
src/store/model.ts
src/views/Home.vue

Adds dataset owner to:
1. Recents menu
2. Breadcrumbs

Show dataset owner

---

src/components/AnnotationBrowser/AnnotationCSVDialog.vue

Don't display entire text
Async work
Add progress indicator on load

Optimized CSV export

---

src/girder/index.ts
src/layout/BreadCrumbs.vue
src/views/Home.vue

When showing user info, show the email instead of the Girder login.

Switched from displaying login to email

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/annotation.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/connections.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/datasetView.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/documentChange.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/history.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/property.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/propertyValues.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/workerInterfaces.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/workerPreviews.py

Those indices are the one used in all the searches that I could find in the codebase.

Add indices to make various searches more efficient

---

src/views/dataset/DatasetInfo.vue

Make the DatasetInfo component more functional and less confusing.

Restyle datasetinfo

---

devops/girder/annotation_client/annotation_client/tiles.py

Allows you to choose a pickle protocol and also to use TIFF for image transfer.

Expose pickle protocol and TIFF file transfer from getRegion

---

devops/girder/annotation_client/requirements.txt

Need to add tifffile to allow all workers to run.

Add tifffile to requirements

---

src/components/AnnotationBrowser/AnnotationProperties/Property.vue
src/components/AnnotationBrowser/AnnotationProperties/PropertyCreation.vue
src/components/AnnotationBrowser/AnnotationProperties/PropertyList.vue
src/store/annotation.ts
src/store/properties.ts

Captures property worker warnings and errors and displays them in the properties panel.

Added property worker warnings and errors

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/helpers/tasks.py
docker-compose.yaml

Added title to jobs so they aren't just all `<unnamed job>`.

Add title to jobs

---

src/components/CustomFileManager.vue

This prevents Vuetify default theme to override it

Use more precise CSS selectors to change icon color

---

src/components/ProgressBarGroup.vue
src/store/annotation.ts
src/store/jobs.ts
src/store/model.ts
src/store/progress.ts

Added toast-style notifications above the progress bars to report warnings and errors for worker jobs.

Add toast notifications

---

src/store/index.ts

Before, when you switch from multiple to single layer visibility and then back, only a single layer remains visible; the UI forgets the previous layer visibilities. Now, we store that information in temporary variables so that the UI acts more like what the user might expect.

Store layer visibilities to provide UI memory

---

src/components/Snapshots.vue

Adds ability to put annotations in the snapshots by capturing the map and cropping.
Also adds the ability to capture a movie with the annotations on it.

Add annotations to snapshots

---

src/utils/conversion.ts
src/views/dataset/NewDataset.vue

Changed max total file size to be in bytes rather than MB.

Changed from MB to bytes

---

src/components/AnnotationViewer.vue

Use option drag to drag annotations.

Added ability to drag annotations

---

src/App.vue
src/components/ZenodoCommunityDisplay.vue
src/components/ZenodoImporter.vue
src/store/model.ts
src/tours/WelcomeTourHome.yaml
src/views/Home.vue

Added a welcome tour that helps you load, view, and analyze a sample dataset.

Added welcome tour with sample dataset

---

src/components/Snapshots.vue

Factorized the scalebar rendering code.
Changed the scaling so that it scales with the size of the image, with reasonable minimum and maximum values.

Scaled scalebar rendering

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/helpers/serialization.py

Fix serialization when a request does not use all the ObjectId field from a model schema

Fix serialization

---

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/annotation.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/connections.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/propertyValues.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/annotation.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/connections.py
devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/propertyValues.py
docker-compose.yaml

Changed compound index to datasetId, then _id, which is a better optimization.
Changed ACL pattern to check the document ID, then just find without checking permissions.

Optimized some database calls
