devops/girder/Dockerfile, package.json, src/components/ContrastHistogram.vue, src/components/ImageViewer.vue, src/components/ValueSlider.vue, src/store/GirderAPI.ts, src/store/index.ts, src/store/model.ts, tsconfig.json
This reduces network fetches when dragging the histogram sliders.  The decreases latency, but still can take up to two image fetches to catch up to the user.
Further improvements will need to improve responsiveness of the server (probably by caching more) and by simulating changes in the client until the server can respond.
=> Reduce network fetches

docker-compose.yaml, package-lock.json, package.json, src/layout/Menu.vue, src/plugins/vuetify.ts, src/store/GirderAPI.ts, src/views/Home.vue, src/views/dataset/NewDataset.vue
This PR attempts to make the UX around selecting data for upload more intuitive and streamlined.
The process looks like this:
1. The user first selects a file or files to upload.
2. The interface automatically selects a reasonable name for the dataset, which the user can choose to edit.
3. The user can optionally enter a description of the dataset.
There is no longer a need to first select a place to upload the data files to, eliminating the necessary two-step process that was in place before.
Depends on #44
=> Streamline the "upload data" page

devops/girder/Dockerfile
This fixes the Dockerfile in light of the `nd2-source` branch having been merged to master.
=> Remove branch specifier from Girder Dockerfile

devops/girder/Dockerfile, src/components/DisplayLayer.vue, src/store/GirderAPI.ts, src/store/model.ts, src/views/dataset/DatasetInfo.vue, tsconfig.json
- The `downlevelIteration` compiler option is needed to allow `for .. of` constructions in the code
- This works by constructing a map of channel numbers to channel names (if those are available), then using this map, with the channel number itself as a fallback, to display the radio button labels for selecting a channel in the viewer's layer controls
=> Display channel names in viewer layer controls

src/components/ImageViewer.vue
This is no longer necessary and seems to interfere with the spinner showing if everything is loaded.
=> Remove the oldTile stack.

src/components/ImageViewer.vue, src/store/images.ts
We were fetching a full range image for the histogram preview.  If this is fetched before the histogram, it used query parameters of min: min, max: max.  If fetched after the histogram, it specified numerical values.  This always prefers min/max in the query for full range.
Also, reduce the number of palette steps -- we are using a linear transform, so additional steps are of no benefit (and could introduce mild artifacts for colors that are do not use the full possible range).
=> Reduce the number of images fetched.

src/components/ImageViewer.vue, src/layout/UserMenu.vue
Remove autofocus attribute of user name.
If we want to autofocus something, this isn't the most useful element.  Plus, Chrome 79+ emits a warning about it.
=> Don't add an image to the ready list multiple times.

src/components/ImageViewer.vue, src/layout/UserMenu.vue, src/store/GirderAPI.ts, src/store/images.ts, src/store/index.ts, src/store/model.ts
This shows an estimated preview of the image under the changing histogram during the interval between when the change is made, and when a new, correct image arrives from the server.
It works by saving the last rendered image for each channel, and adjusting the color contrast in that image via an SVG filter applied as a canvas filter.
=> Draw a "histogram preview" image while changing the histogram bounds

src/layout/BreadCrumbs.vue
Instead of showing "stemmedia_8well_bottomright_005.nd2 / 2020-02-11 / Explore", this now shows "Dataset: stemmedia_8well_bottomright_005.nd2 Configuration: 2020-02-11".
This resolves #38.
Example, before:
Example, after:
=> Improve the breadcrumbs.

src/components/ImageViewer.vue
If you have a layer with a slice that has an offset, then at the ends of the range, that layer may not have an image.  Don't throw an exception in that case.
=> Guard against a layer that doesn't contain an image.

src/components/DisplaySlice.vue, src/components/SwitchToggle.vue
This fixes the CSS of the two-state switch controls.
Instead of this:
it now looks like this:
=> Improve CSS on switch controls.

src/components/ContrastHistogram.vue, src/components/ImageViewer.vue
=> If the histogram is empty, don't clamp it.

src/components/ImageViewer.vue, src/components/SwitchToggle.vue, src/components/ViewerToolbar.vue, src/views/dataset/configuration/Viewer.vue
When the composition control was moved to the bottom (#59), proper scrolling was broken -- scrolling the toolbar needs to not scroll the image area.
=> Fix scrolling in toolbar.

package-lock.json, package.json, src/components/DisplayLayer.vue, src/components/ImageViewer.vue, src/components/ViewerToolbar.vue, src/store/GirderAPI.ts, src/store/images.ts, src/store/index.ts, src/store/model.ts, src/views/dataset/configuration/Configuration.vue, src/views/dataset/configuration/Viewer.vue
This PR adds checkboxes to control whether to unroll the images contained along the XY, Z, and/or T dimensions.
You can use [small3.tar.gz](https://github.com/Kitware/UPennContrast/files/4653464/small3.tar.gz) to test this feature.
~Typechecking is currently failing, though the application does work. Before merging I will fix the typechecking, but I wanted to get a review before doing so (as it may be a bit involved).~ **UPDATE:** typechecking fixed now (2020-05-21 17:54)
=> Add checkboxes to toggle unrolling by XY, Z, and T

src/store/GirderAPI.ts
On multi-file data sets, this could result in errors.
=> Fix how the cache key is computed for full-contrast images.

src/store/GirderAPI.ts, src/store/index.ts
If you unroll two or more axes, the first axis is unrolled horizontally and the rest vertically.
This may not be ideal, especially if you unroll three axes.  For three axes, it might be better to determine which of axes 1&2 x axis 3 and axis 1 x axes 2&3 are squarer.
Further, the axes are unrolled in the order they are reported by the file, which isn't guaranteed to be the order of the axes in the UI.  For instance, in normmedia_8well_col2_livecellgfp.nd2, there are 6 XY, 7 Z, and 4 T values.  Since T is reported first, it unrolls T horizontally and XY or Z vertically, but we list time third in the UI.
=> If unrolling two or more axes, layout in a grid.

src/store/GirderAPI.ts
Image files that contain a single image don't report a frames record.  Supply a list of one value so that these images can be used.
=> Use image files with have no frames.

src/components/ImageViewer.vue
If the fully adjusted layer finished rendering before the preview layer, the spinner could remain spinning even though it was done.
=> Fix waiting spinner.

src/store/GirderAPI.ts
This was using every pixel to compute histograms, which is very slow on large images.  Instead, use a maximum image size of 2048 x 2048.
=> For large images, use a reduced image for histograms.

src/components/ImageViewer.vue
If the first layer is set to an offset such that there is no image available (e.g., at z = 0 with an offset of -1), the drawing function would through an exception.  Now, first the first layer with an available image.
=> Fix an issue if the first layer had no images.

src/layout/UserMenu.vue
Somehow, the user menu is beneath the image.  Increase the z-index to fix it.
=> Fix the user menu z-index

package-lock.json, package.json, src/components/ImageViewer.vue, src/store/GirderAPI.ts, src/store/index.ts, src/store/model.ts, src/utils/README.txt, src/utils/setFrameQuad.d.ts, src/utils/setFrameQuad.js
This has some tunable parameters to fetch more background quad images or use more or less texture memory.  Using more background textures results in some texture memory loading spikes that manifest as some initial hesitation in z scrolling, but produce nicer images.
=> Use background quads for smoother transitions.

devops/girder/provision.py, src/components/ImageViewer.vue, src/store/index.ts, src/utils/setFrameQuad.js
This uses smaller but more textures.
This also adjusts a cache setting on the server to allow caching more tile frame textures.
=> Change tile frames defaults.

src/store/GirderAPI.ts
When asking for a url with a style with multiple frames, make sure the base frame is the first one.  This can reduce url variations, allowing somewhat more browser caching.  It probably won't have much effect until we use a max-merge histogram for max-merge views.
=> More uniform urls.

docker-compose.yaml
For some versions of Docker on OSX, adding delegated speeds up file access.  It should do no harm on other systems.
=> Add delegated to volume mounts.

src/components/ImageViewer.vue, src/girder/index.ts, src/store/GirderAPI.ts, src/store/index.ts, src/utils/setFrameQuad.js
Now, precaching the tile frames can be done by calling the tile_frames/quad_info endpoint with cache=schedule.  To match what is done in the javascript side, this endpoint needs to be called per channel with frameBase=<channel>, frameStride=<number of channels>, frameGroup=<IndexZ || 1>, frameGroupStride=<IndexZ / IndexC>.  This is in addition to the defaults used in this project defined in src/store/index.ts around line 745.
To make this more convenient, we could add (to large_image) a special value for frameBase which would schedule all tile_frames based on this heuristic.
=> Use the quad_info endpoint for tile_frames.

docker-compose.yaml
The girder container can access it as is, so there is no need.
=> Don't expose mongo's port.

devops/girder/annotation_client/annotation_client/tiles.py
They aren't all guaranteed to exist, depending on the tile source and format.
Fixes #210.
=> Guard index values.

src/store/index.ts
Before, every time the user logged in, we replaced the rest client class with a new instance.  This made it hard to share the client in multiple spots.
=> Fix relogging in.

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/system.py, src/store/GirderAPI.ts, src/store/index.ts, src/views/dataset/NewDataset.vue
Once the endpoint has run, this should "just work" to make max-merge display more efficient.
max-merge tiles are loaded on demand (no preview sprite level).  In a local timing test, about half of the time is spend fetching the tile and half spent encoding it to png.  We might want to revisit either (a) png compression level options, or (b) whether the 'fast' layers for rough adjustment need to be png or if they could be jpg.
To hook up sprite (tile frame) support would take more effort.
We probably want to trigger running this endpoint at the same time we trigger generating the tile_frames.
=> Add an endpoint and support for generating max-merge substitutes.

src/components/ViewerToolbar.vue, src/store/GirderAPI.ts, src/views/Home.vue
This also fixes some needless updates that were resulting in spurious warnings in the console.
This change shouldn't be noticeable except for less noise in the console.
=> Only use the first image in a folder.

.gitignore, src/App.vue
Bug found: opening both right panels together ("Snapshot" and "Browse annotations") creates a UI bug
Fixed it by allowing only a single right panel to be open at a time
Also added `/assetstore` and `/db` to `.gitignore`
=> Bug fix: right panel overlap

src/components/DisplayLayer.vue, src/store/index.ts
Before, you could occasionally switch to single layer mode and have two or zero channels showing.
This was caused by calling a function to toggling the layer that checked if the target event was an input element instead of just doing it.
=> Fix some issues with layers not always turning on or off.

src/components/ImageViewer.vue
This actually leaves "0" to unrotate the image (we can remove it if desired), mainly as a demonstration of how to keep some bindings.
Resolves #159.
=> This removes geojs keyboard bindings.

src/store/index.ts
Specifically, Vue sometimes makes the image list an observable and then it doesn't compare with the non-observable list of the same items. Instead, compare the entries in the list.
This fixes #307.
=> Fix an issue when comparing histogram image lists.

src/store/index.ts, src/store/model.ts
Reformat getLayerHistogram to make it clearer.
Fix an infinite recursion.
Closes [#310](https://github.com/Kitware/UPennContrast/issues/310)
=> Clean the debounce of getLayerHistogram

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/helpers/connections.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/test/test_connections.py, src/components/AnnotationViewer.vue, src/store/model.ts, src/utils/annotation.ts
Z coordinate of IGeoJSPoint was used inconsistently, being often undefined and causing bugs.
Closes [#304](https://github.com/Kitware/UPennContrast/issues/304)
=> Remove z coordinate from IGeoJSPoint

src/components/AnnotationBrowser/AnnotationList.vue, src/components/AnnotationViewer.vue, src/utils/annotation.ts
When clicking in the view, the annotation becomes hovered if no tool is selected
Scroll to annotation in the browse annotation panel when clicking an annotation
Fix minor style bug on hover
Closes #322 
Closes #321
=> Bring to annotation in the browser on click in the view

src/components/AnnotationViewer.vue
It didn't take into account different types of IDisplayLayer & unrolling
The logic should now be fixed
Fixes [the bug mentionned ](https://github.com/Kitware/UPennContrast/pull/319#issuecomment-1335176242) in PR #319
=> Fix layerShouldDisplayAnnotation

src/App.vue, src/layout/BreadCrumbs.vue
Specifically, long filenames wrapped poorly, and the application tile would get truncated.
=> Fix some top bar formatting.

src/components/ContrastHistogram.vue
If the second most common value in a histogram is rare compared to the most common value, increase the vertical scale.
=> Better scale sparse histograms on sparse images

src/store/GirderAPI.ts, src/utils/parsing.ts, src/views/dataset/MultiSourceConfiguration.vue
Add compositing option when importing compatible a single nd2 file.
Change the UI.
Closes  #244
=> Add compositing

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/annotation.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/connections.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/annotation.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/connections.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/propertyValues.py, src/components/AnnotationBrowser/AnnotationCSVDialog.vue, src/components/AnnotationBrowser/AnnotationExport.vue, src/components/AnnotationBrowser/AnnotationImport.vue, src/components/AnnotationBrowser/AnnotationList.vue, src/components/AnnotationViewer.vue, src/components/ContrastHistogram.vue, src/components/ImageViewer.vue, src/components/Snapshots.vue, src/store/AnnotationsAPI.ts, src/store/PropertiesAPI.ts, src/store/annotation.ts, src/store/filters.ts, src/store/model.ts, src/store/properties.ts, src/utils/annotation.ts, src/utils/download.ts
The import / export buttons are currently in the annotation browser but can be moved in the future (but after PR #333 to avoid conflicts)
Fix some performance issues: rework annotation viewer, use Maps and Sets
Fix an untracked bug which made annotation connections between annotations of different datasets possible
Change style of annotations instead of removing and adding them
Add some endpoints for bulk POST and DELETE
Clean connections and property values orphans when deleting annotations
Add downloadToClient helper function
Annotation property values exported before/after PR #333 but computed with a worker after/before PR #333 can't be imported
This problem shouldn't be a problem for final users if the update of the workers is done at the same time as the update of the frontend
A …
=> Add import/export feature

src/components/ValueSlider.vue, src/store/index.ts
If you switch frames quickly, multiple histogram calls are made to the server.  There was a bug that if there was a pending histogram call, the next histogram call might be skipped.
Fixes #356.
=> Fix an issue debouncing histogram calls.

devops/girder/annotation_client/annotation_client/tiles.py
To get the tiles internal metadata in a worker, simply do:
```python
import annotation_client.tiles as tiles
datasetClient = tiles.UPennContrastDataset(apiUrl=apiUrl, token=token, datasetId=datasetId)
internalMetadata = datasetClient.tilesInternal
```
=> Add tilesInternal to UPennContrastDataset in client

devops/girder/Dockerfile
We were inconsistently using master for large_image, but the versioned packages for all of the sources.  We should do one or the other; this uses the master.  Otherwise, we should have just pip installed large_image[all] (and girder[mount]) without cloning the large_image repo.
Note, currently using large_image master enables image conversion on the local instance rather than using the worker.  This will make it easier to test transcoding images on a deployed instance to see if that results in substantial speed gains.
=> Adjust docker to use the latest master of large_image.

src/utils/annotation.ts
Hovered style wasn't different from base style for lines
Change stroke width and color when hovering annotations
Close #464
=> Change style of hovered annotations

package-lock.json, package.json, src/components/ImageOverview.vue, src/components/ImageViewer.vue, src/components/Snapshots.vue, src/components/ViewerSettings.vue, src/store/GirderAPI.ts, src/store/girderResources.ts, src/store/images.ts, src/store/index.ts, src/store/jobs.ts, src/store/model.ts, src/views/dataset/MultiSourceConfiguration.vue
To be merged after the overview PR #507 
Close #502
=> Histograms precache

src/components/ImageViewer.vue, src/components/ScaleSettings.vue, src/components/ViewerSettings.vue, src/store/AnnotationsAPI.ts, src/store/GirderAPI.ts, src/store/PropertiesAPI.ts, src/store/annotation.ts, src/store/index.ts, src/store/model.ts, src/store/properties.ts, src/utils/conversion.ts, src/views/configuration/ConfigurationInfo.vue, src/views/configuration/DuplicateImportConfiguration.vue, src/views/configuration/ImportConfiguration.vue, src/views/configuration/NewConfiguration.vue, src/views/dataset/DatasetInfo.vue
Add a new panel in the collection view
Make scalebar clickable, open a dialog to tweak scales
I added most of the features of issue 498:
- In the collection view, the user can set the values for the different scales
- In the image viewer, the user can open a dialog by clicking on the scalebar to have more options. In this dialog, the scale is saved in the dataset view and the user has the option to save the scale in collection and to reset to dataset default. It behaves like the contrasts.
- The scalebar uses the pixel size given in the dataset view or in the configuration.
- Workers have access to scales: `params["scales"]["pixelSize"]` contains both `value` and `unit`
Close #498
=> Add image scale settings

devops/girder/annotation_client/annotation_client/annotations.py
I added `createMultipleConnections` function which can be used in the exact same way as `createMultipleAnnotations` but with connections instead of annotations.
To see what a connection should look like, give a look at `ConnectionSchema` in `devops\girder\plugins\AnnotationPlugin\upenncontrast_annotation\server\models\connections.py`.
I copy-paste it here to avoid diving into the sources:
```python
class ConnectionSchema:
tagsSchema = {
'type': 'array',
'items': {
'type': 'string'
}
}
connectionSchema = {
'$schema': 'http://json-schema.org/schema#',
'id': '/girder/plugins/upenncontrast_annotation/models/annotation_connection',
'type': 'object',
'properties': {
'label': {'type': 'string'},
'parentId': {'type': 'string'},
'childId': {'type': 'string'},
'datasetId': {'type': 'string'}, …
```
=> Add createMultipleConnections function to client

src/components/WorkerInterfaceValues.vue, src/store/model.ts
Enable controlling the UI of the frontend through the worker interface to some extent.
For example, to add a placeholder for a text item in the interface, one can have this item in its interface:
```python
'Batch XY': {
'type': 'text',
'vueAttrs': {
'placeholder': 'ex. 1-3, 5-8'
}
},
```
Another example with more attrs:
```python
'Batch XY': {
'type': 'text',
'vueAttrs': {
'placeholder': 'ex. 1-3, 5-8',
'outlined': True,
'prefix': 'My batch'
}
},
```
To get a list of available `vueAttrs`, look at the code in `WorkerInterfaceValues.vue`.
Here, there is a component for each item type.
For example `number` items becom `v-slider` components, `text` become `v-text-field` components...
Items starting with `v-` are vuetify components and the list of available attributes are in the Vue 2 docs …
=> Add vue attrs to worker interface

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/helpers/tasks.py, devops/girder/provision.py
The worker needs to run in the same network as the rest of the docker containers OR girder must be publicly visible to the worker and to girder_worker both.  By not specifying the network mode of the worker, girder_worker assigns it the same network as girder_worker's container. By specifying http://girder:8080/api/v1 as the alternative worker URL, this is reachable from within that network.
=> Fix networking mode for worker.

src/store/GirderAPI.ts
Fix issue mentioned in [this comment](https://github.com/Kitware/UPennContrast/pull/582#pullrequestreview-1696172976)
The getItems function used to fetch only the first 50 items
=> Fix getItems limit

devops/girder/Dockerfile
Girder's default docker uses a base image that has python 3.7 and doesn't explicitly override it.  This uses a girder test docker that has multiple version of python.  Use 3.11
=> Use a docker with newer python

devops/girder/Dockerfile, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/__init__.py
Reorders the Girder Dockerfile to allow for the girder.cfg file to be read and acted upon properly.
=> Reorder docker

src/components/AnnotationBrowser/AnnotationCSVDialog.vue
CSV now uses 1 indexing for XY, Z, T to match the interface.
=> Changed CSV to 1 indexing

src/components/ImageViewer.vue
Close #657 
It was caused by an error thrown by oldWidgetLayer.deleteWidget when the layer was deleted
=> Fix black screen when changing dataset

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/datasetView.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/datasetView.py, src/components/ViewerToolbar.vue, src/main.ts, src/store/GirderAPI.ts, src/store/index.ts, src/store/model.ts, src/views/datasetView/Viewer.vue
If you stay more than 5 seconds at the same location, the last location is saved in the dataset view
When reopening the the same dataset view, the location will be the same as before
If the url query contains a location (for example `z=9`), it will override the last location saved in the dataset view
Close #654
=> Make dataset view remember last location

devops/girder/annotation_client/annotation_client/annotations.py, devops/girder/annotation_client/annotation_client/workers.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/propertyValues.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/propertyValues.py
Close #550
This PR is based on PR #651 to avoid a conflict
It should be merged after
You need to rebuild girder to see the effects of this PR
The workers can use the function `addMultipleAnnotationPropertyValues()`
For convenience, here is the signature and documentation of this function:
```python
def addMultipleAnnotationPropertyValues(self, entries):
"""
Save one or multiple computed property values for the specified annotations
The recursive_dict_of_numbers can be (and usually is) just a number
:param list entries: A list of property values for an annotation. Each entry is of type { "datasetId": string, "annotationId": string, "values": { [propertyId: string]: recursive_dict_of_numbers } }
"""
```
=> Add an endpoint for adding multiple annotation property values

src/components/ImageOverview.vue, src/components/ImageViewer.vue
Fix the scale of the image overview in the minimap
Another very small change: the scalebar throws errors in the console when the scale is at 0 and the scalebar doesn't show up
So I removed the scalebar when the scale is 0 to avoid errors, this shouldn't change anything for the user
=> Fix overview scale

patches/mousetrap+1.6.5.patch
Before moving to vite, a declaration of "i" was probably leaking into the plugin
If this still doesn't work, make sure the patch is applied by running `npm run dev -- --force`
D3 and mousetrap should be upgraded / replaced instead of being patched
Close #668
=> Add a patch to fix mousetrap

src/store/annotation.ts, src/tools/creation/templates/AnnotationConfiguration.vue
There was a confusion with 0 indexing and 1 indexing:
- 1 indexing is used for the user interface and in tool configuration
- 0 indexing is used everywhere else inside the app
Close #704
=> Fix indexing in tool creation and annotation creation

src/components/AnnotationBrowser/AnnotationList.vue
Do not show annotation ID, etc., by default because they clutter the interface.
=> Set default list headers

src/components/AnnotationBrowser/AnnotationList.vue
@bruyeret I changed the selection thing for the columns to something that I think is more intuitive. It basically works, but it doesn't look quite as good when the interface is in light mode. The problem is that when a chip is selected, it looks like it is active, even if it is not active. In dark mode, it looks fine because the white outline dominates. But the underlying issue is still there. I couldn't figure out how to change the styling. Anyway, overall, it is still an improvement, so we can also just merge the PR, but if you have any quick fixes, go for it!
=> Changed to chip selection

public/config/templates.json, src/tools/creation/ToolTypeSelection.vue
@bruyeret I made the tool list bigger and made it come from a button. I think the interface is a bit more discoverable now, because the list of items was so long. The only problem is that the floating panel is now to the left of the button, would be better to the right of the button, I think. Also, we have a lot of old tools or non-functional tools. Perhaps we can comment them out for now?
=> Put tool list in bigger panel

devops/girder/provision.py, src/components/CustomFileManager.vue, src/components/ImageOverview.vue, src/components/ImageViewer.vue, src/store/GirderAPI.ts, src/store/index.ts, src/store/model.ts, src/utils/setFrameQuad.ts, src/views/dataset/NewDataset.vue
The default is now the Private folder for everything.
Also fix the datasets that are uploaded in the private folder, as the images didn't send the `girder-token` cookie because of the `crossOrigin` setting of images that was badly set.
Also fix the default CORS allowed origins in girder, because a simple wildcard is not compatible with `crossOrigin="use-credentials"`.
For exisiting builds, that use a different IP for the front end and girder:
In girder (http://localhost:8080/):
- Go to Admin Console -> Server Configuration
- Go to Advanced Settings at the bottom and find `CORS Allowed Origins` setting
- Replace the `*` with the full adress of the backend (for example `http://localhost:5173` or `http://localhost:*`), or even `**` if it is in a private network
- Save the settings
Close #739
=> Use private folder by default

devops/girder/annotation_client/annotation_client/tiles.py
Default was 50, so if there were more than 50 files in the folder, you were not getting everything.
=> Change limit to 0 (no limit)

src/store/AnnotationsAPI.ts, src/store/annotation.ts, src/store/model.ts, src/store/properties.ts, src/tools/ToolEdition.vue, src/tools/creation/ToolConfiguration.vue, src/tools/creation/ToolCreation.vue
Now, if you label an automated worker docker container like this:
```
LABEL isUPennContrastWorker="" \
isAnnotationWorker="" \
interfaceName="Connect to Nearest" \
interfaceCategory="Connections" \
description="Connects objects to each other based on distance" \
advancedOptionsPanel="False" \
annotationConfigurationPanel="False" \
defaultToolName="Connect to Nearest"
```
it will turn off the Advanced Options Panel, configuration panel, and will auto-name with "Connect to Nearest".
Closes #784
=> Configure automated tool creation panel

src/components/AnnotationBrowser/AnnotationProperties/PropertyCreation.vue
This PR allows the user to create properties even if no tag is specified. This helps if you want to compute, say, area for all polygon objects at once.
Closes #788 
Closes #787
=> Allow no tag property creation

src/components/AnnotationBrowser/AnnotationList.vue, src/store/annotation.ts
Allows you to delete all annotations that are not currently selected.
Closes #762
=> Add delete unselected button

src/components/AnnotationWorkerMenu.vue, src/store/model.ts, src/store/properties.ts
Most workers do not have preview functionality, but the preview button is always showing. This PR hides the preview button unless the docker image has a "hasPreview" label set to True.
=> Hide preview button

src/tools/creation/templates/AnnotationConfiguration.vue
Autotags will only be applied to non-advanced Annotation Configuration
Fixes #766
=> BUG: Fix autoTags

src/store/model.ts, src/views/dataset/MultiSourceConfiguration.vue
Added typescript definitions to handle the transformation matrix.
I also changed the logic a little bit. Instead of just inverting the position, I rounded the transformation matrix to a straight inversion. This inverted the entire image (although still aligned). I stuck with rounding the transformation matrix because then it will more closely match what would happen of the transformation matrix was actually applied.
I still don't have an example of an image with more interesting transformation values to fully test out the code, but I think it is a strict improvement from what was there before.
=> Nd2 camera transform

devops/girder/annotation_client/annotation_client/utils.py, src/components/AnnotationWorkerMenu.vue, src/store/annotation.ts, src/store/jobs.ts, src/store/model.ts
Added an error alert. It allows you to send an error using sendError just like sendProgress. This way, the worker can communicate an error to the user. We may also want to send warnings to the user through the same interface, perhaps by using a warning flag or something.
=> Handle worker error

src/components/AnnotationViewer.vue
An extra watch in AnnotationViewer was causing everything to be drawn twice.
=> Removed a duplicate redraw

src/components/AnnotationViewer.vue
Used an internal variable to ensure that we don't double draw. Probably better in the long term to change this to an internal store to coalesce the watchers, but that seemed to be a bit too much for now.
=> Added back watcher for displayedAnnotations

package.json, pnpm-lock.yaml
Bump geojs to 1.12.6. Increased performance for large numbers of annotations.
=> Bump geojs

src/components/AnnotationBrowser/AnnotationList.vue
Annotation List is slow to update with large numbers of annotations because it triggers a redraw from every mouseover event. Change this to just update based on a click if you have over 5000 annotations.
=> Performance enhancement: alter hover behavior

src/views/dataset/MultiSourceConfiguration.vue
The getTiles API from large_image expects the field large_image to be set when recovering the tiles, but due to the S3 assetstore, that field can take a bit of time to be set.
Retry that function a few times (10) if it fails to wait for that field to be set.
=> Fix large image upload with S3 assetstore

src/components/AnnotationViewer.vue, src/components/ImageViewer.vue, src/store/model.ts
Annotation selection and creation was very slow with large numbers of annotations because interaction annotations were on the same layer as the main annotations. I created a separate interactionLayer to capture all the interactions, making all these interactions much faster.
=> Speed selection and creation

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/system.py, src/components/ImageViewer.vue, src/components/ProgressBarGroup.vue, src/store/AnnotationsAPI.ts, src/store/GirderAPI.ts, src/store/annotation.ts, src/store/model.ts, src/store/progress.ts, src/utils/fetch.ts, src/utils/setFrameQuad.ts
Added a new ProgressBarGroup component and progress store to help manage progress bars across the application.
Converted all existing progress bars to use new framework.
Updated max-merges so that their progress is captured (before it was not, leading to a gap).
Created both ID-tracked progresses for longer computations and reactive progresses for quick updates.
Next steps could be to duplicate annotation worker progresses and other deletion/drawing/import/export updates that can be slow.
=> Progress bars

src/components/ImageViewer.vue
People wanted a way to "lock" the view so that it wouldn't move around when doing e.g. SAM segmentation.
=> Add display lock button

src/App.vue, src/components/AnalyzePanel.vue, src/components/AnnotationBrowser/AnnotationBrowser.vue, src/components/AnnotationBrowser/AnnotationList.vue, src/components/AnnotationBrowser/AnnotationProperties.vue, src/components/AnnotationBrowser/AnnotationProperties/PropertyCreation.vue, src/components/AnnotationBrowser/AnnotationProperties/PropertyList.vue
Updated the UI for "Measure Objects":
1. Removed the separate Measure objects panel.
2. Moved it to a button on the "Properties" collapsible panel in the objects panel.
3. When you close the new "Measurements" dialog, it automatically opens the "Properties" collapsible panel, which makes it more discoverable.
4. Minor UI improvements.
=> Refactored the object panel UI

package.json, pnpm-lock.yaml, src/App.vue, src/components/DisplayLayers.vue, src/components/ImageViewer.vue, src/components/ViewerToolbar.vue, src/main.ts, src/plugins/tour-trigger.directive.ts, src/plugins/tour.scss, src/plugins/tour.ts, src/plugins/tourBus.ts, src/store/model.ts, src/tours/AdvancedUploadTour.yaml, src/tours/IntroViewerTour.yaml, src/tours/TOURS.md, src/tours/testTimelapseTour.yaml, src/views/Home.vue, src/views/dataset/DatasetInfo.vue, src/views/dataset/MultiSourceConfiguration.vue, src/views/dataset/NewDataset.vue, vite.config.js
Check TOURS.md for a description.
Adds a declarative tour manager. You can specify a tour with a clear, easy-to-generate YAML file that simply declares the steps. You then just tag the relevant parts of the template as described in TOURS.md. The tour manager then turns that into a Shepherd tour—no need to edit any script. This should make it relatively easy to make new tours and maintain existing tours, especially using LLMs.
=> Added a simple user tour

src/components/ImageViewer.vue
We were having an issue where the palette icon for the contrast adjustment was sometimes not displaying. It seems to be an issue with the v-if conditional. I changed it to a :disabled logic, and it works fine now.
=> Fixed palette icon

src/plugins/tour.ts, src/tours/IntroViewerTour.yaml
Set scrollto to false to avoid the interface shifting around unpredictably. Reduced timeout for the rotation to avoid user confusion. Swapped order of pan and zoom so that hopefully the user zooms first to make panning possible.
=> Updated scrolling behavior and viewer tour

src/views/dataset/MultiSourceConfiguration.vue
Added support for RGB images by parsing bands.
In the process, also refactored the generated multi-source JSON to be more explicit about sources for each frame. This was done to avoid a bug in the way large_image was previously parsing things in the non-composited case @manthey. Problem is solved for our scenario, so all good, but I can try and reproduce the bug if you are curious.
=> Rgb support

devops/girder/annotation_client/annotation_client/tiles.py, src/components/ImageViewer.vue, src/components/LargeImageDropdown.vue, src/components/ViewerToolbar.vue, src/girder/index.ts, src/store/GirderAPI.ts, src/store/annotation.ts, src/store/girderResources.ts, src/store/index.ts, src/utils/girderSelectable.ts, src/views/datasetView/Viewer.vue
Adds support for multiple large_images as the raw data. This allows for e.g. gaussian blurring, registration, and other types of pixel-level manipulation.
To test, run
```
docker build -f ./workers/annotations/gaussian_blur/Dockerfile -t annotations/gaussian_blur:latest ./workers/annotations/gaussian_blur/
```
Then you will have a new Gaussian Blur worker that can be used to do some processing.
Some future work could be:
1. To create either a subsection of tools or even a whole other panel to select these particular image processing workers.
2. Build a few more abstractions for workers to list and access various large_images more easily.
3. When the dataset refreshes, maintain the zoom level.
4. Watch out for quotas.
=> Multiple large images

src/components/ViewerToolbar.vue
Not sure how this got changed, but changed the style back to overflow-y.
=> HOTFIX: added back scrollbar

src/components/ChannelCheckboxGroup.vue, src/components/WorkerInterfaceValues.vue, src/store/model.ts
Allows a checkbox group for channels as a worker interface element.
Can be added using e.g.:
```
'All channels': {
'type': 'channelCheckboxes',
'tooltip': 'Blur selected channels.',
'displayOrder': 2,
},
```
=> Added channel checkbox group to worker interface

src/components/WorkerInterfaceValues.vue
Added guard on tool being undefined.
Added guard in case tool.values.workerInterfaceValues is not defined.
=> Fixed bugs in loading default worker menu items

src/store/jobs.ts
Adding a 45 second timeout ensures that long-running tasks will remain connected despite proxy/load balancer timeouts.
=> Add timeout to stream request

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/annotation.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/connections.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/datasetView.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/property.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/workerInterfaces.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/api/workerPreviews.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/annotation.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/connections.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/datasetView.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/property.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/workerInterfaces.py, devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/server/models/workerPreviews.py
The models defined in AnnotationPlugin used to define a method `update()` used in its API, but this actually overrides a base Girder BaseModel method used to update the document.
This prevented users from being deleted.
=> Restore Girder BaseModel update method in AnnotationPlugin

src/store/properties.ts
Unit tests have ":test" in the image name; this new code filters those out of the list of images.
=> Remove all test images from the worker list

src/components/AnnotationBrowser/AnnotationList.vue, src/store/annotation.ts, src/store/progress.ts
Users have noticed that deleting large number of annotations takes a long time. We should of course fix that :), but for now, we should at least provide some progress indicator so that users know that a deletion is occurring.
=> Added progress bar and indicators to annotation deletion

src/components/AnnotationWorkerMenu.vue, src/tools/toolsets/Toolset.vue
Prevents the worker menu from going off screen slightly, which was very annoying. Calls updateDimensions after content is loaded.
=> Fix worker menu positioning

src/store/GirderAPI.ts, src/views/dataset/MultiSourceConfiguration.vue
Allows for the uploading of OIB files.
Does so by explicitly asking for a conversion to large_image. Not sure why that's required, but it doesn't work without it.
=> Handle OIB files

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/__init__.py, src/girder/index.ts, src/store/GirderAPI.ts, src/views/dataset/NewDataset.vue
Admin can make an api_key for a particular user to enable a different upload quota.
=> Enable api_keys for larger file uploads

src/utils/polygonSlice.ts
We had a problem where if you run the blob edit tool over the polygon "seam", it would have unpredictable behavior. Now, it will perform the expected behavior. It tests the two potential edit options and chooses the one whose centroid is closest to the original polygon's centroid. This heuristic seems to generally correspond to what people expect the tool to do.
=> Fixed blob edit tool to work across polygon "seam"

src/plugins/tour.ts, src/store/model.ts, src/tools/creation/templates/AnnotationConfiguration.vue, src/tours/WorkingWithTags.yaml
Introductory tour that shows up when the AnnotationConfiguration.vue mounts and displays the TagPicker component.
Also added an `isTourActive` check to `tour.ts` to ensure that we don't have collisions between tours.
=> Tag intro tour

devops/girder/plugins/AnnotationPlugin/upenncontrast_annotation/system.py
When we have converted an image and then create a max-merge cache, we end up with a girder item named "multi-source2.json".  When we ask to create the max-merge cache, by the time the multi-source max-merge cache gets processed, the name of the file ends up ending in json, and large-image prefers the alphabetically first openslide source over the tiff source, which fails to read all of the channels and other frames. In this case, require that we use the tiff source for reading the converted file.
Resolves #950
=> Fix creating a max-merge cache from a converted image.

src/components/AnnotationBrowser/AnnotationProperties/PropertyCreation.vue, src/store/model.ts
When finding the list of properties, include images labeled with annotationShape="any".
=> Allow for "any" as a property shape

src/components/AddDatasetToCollection.vue, src/layout/BreadCrumbs.vue
Before, when you try to upload a dataset to add it to an existing collection, it wouldn't show the file dropzone for uploading because there was no default selected location. Changed it to use the user's private folder by default, solving the problem.
=> Set default location to private folder when uploading dataset to existing collection
